import { customerSchema, categoryOptions, genderOptions } from "./types/customer-types"

export { categoryOptions, genderOptions }

const customersData = [
  {
    id: "KH-001",
    name: "Nguyễn Văn An",
    category: "real_estate",
    address: "123 Lê Lợi, Quận 1, TP. Hồ Chí Minh",
    email: "nguyenvanan@gmail.com",
    phone: "0901234567",
    gender: "male",
    note: "Khách hàng VIP, quan tâm đến dự án ven biển Đà Nẵng.",
  },
  {
    id: "KH-002",
    name: "Trần Thị Bích",
    category: "beauty",
    address: "45 Nguyễn Huệ, Quận Hải Châu, Đà Nẵng",
    email: "tranthibich@gmail.com",
    phone: "0912345678",
    gender: "female",
    note: "Chủ chuỗi spa 3 cơ sở, cần tư vấn mở rộng.",
  },
  {
    id: "KH-003",
    name: "Phạm Minh Cường",
    category: "technology",
    address: "67 Đinh Tiên Hoàng, Quận Bình Thạnh, TP. Hồ Chí Minh",
    email: "phamcuong@techvn.com",
    phone: "0934567890",
    gender: "male",
    note: "CEO startup fintech, đang tìm văn phòng mới.",
  },
  {
    id: "KH-004",
    name: "Lê Thị Dung",
    category: "education",
    address: "89 Trần Phú, Quận Hoàn Kiếm, Hà Nội",
    email: "ledung.edu@gmail.com",
    phone: "0945678901",
    gender: "female",
    note: "Hiệu trưởng trường tư thục, quan tâm đến cơ sở mới.",
  },
  {
    id: "KH-005",
    name: "Võ Thanh Hải",
    category: "construction",
    address: "12 Hùng Vương, Quận Ninh Kiều, Cần Thơ",
    email: "vothanhai@xaydung.vn",
    phone: "0956789012",
    gender: "male",
    note: "Giám đốc công ty xây dựng, đã hợp tác 3 dự án.",
  },
  {
    id: "KH-006",
    name: "Hoàng Lan Anh",
    category: "retail",
    address: "234 Lê Thánh Tông, Quận Ngô Quyền, Hải Phòng",
    email: "hoanglanhanh@gmail.com",
    phone: "0967890123",
    gender: "female",
    note: "Chuỗi cửa hàng thời trang 5 chi nhánh miền Bắc.",
  },
  {
    id: "KH-007",
    name: "Đặng Văn Khoa",
    category: "logistics",
    address: "56 Quang Trung, TP. Quy Nhơn, Bình Định",
    email: "dangvankhoa@logistics.com",
    phone: "0978901234",
    gender: "male",
    note: "Giám đốc công ty vận tải, fleet 50 xe tải.",
  },
  {
    id: "KH-008",
    name: "Nguyễn Thị Mai",
    category: "healthcare",
    address: "78 Nguyễn Trãi, Quận Thanh Xuân, Hà Nội",
    email: "nguyenthimai.bs@gmail.com",
    phone: "0989012345",
    gender: "female",
    note: "Bác sĩ, muốn mở phòng khám chuyên khoa nhi.",
  },
  {
    id: "KH-009",
    name: "Lý Đức Thắng",
    category: "finance",
    address: "90 Đinh Lễ, Quận Hoàn Kiếm, Hà Nội",
    email: "lyducthang@bank.vn",
    phone: "0901234568",
    gender: "male",
    note: "Trưởng phòng tín dụng ngân hàng, khách hàng cũ.",
  },
  {
    id: "KH-010",
    name: "Trương Thị Kim Oanh",
    category: "hospitality",
    address: "11 Phạm Văn Đồng, Nha Trang, Khánh Hòa",
    email: "truongkimoanh@resort.com",
    phone: "0912345679",
    gender: "female",
    note: "Chủ resort 4 sao ven biển, mở rộng thêm villa.",
  },
  {
    id: "KH-011",
    name: "Bùi Quang Vinh",
    category: "manufacturing",
    address: "23 KCN Biên Hòa, Đồng Nai",
    email: "buiquangvinh@factory.vn",
    phone: "0923456789",
    gender: "male",
    note: "Giám đốc nhà máy sản xuất đồ gia dụng.",
  },
  {
    id: "KH-012",
    name: "Phan Thị Hồng",
    category: "agriculture",
    address: "Xã Ea Kly, Huyện Krông Pắk, Đắk Lắk",
    email: "phanhong.farm@gmail.com",
    phone: "0934567891",
    gender: "female",
    note: "Chủ trang trại cà phê 50 ha, xuất khẩu sang Châu Âu.",
  },
  {
    id: "KH-013",
    name: "Cao Minh Tuấn",
    category: "entertainment",
    address: "156 Võ Văn Kiệt, Quận 1, TP. Hồ Chí Minh",
    email: "caominhtuan@media.vn",
    phone: "0945678902",
    gender: "male",
    note: "Giám đốc sản xuất chương trình truyền hình.",
  },
  {
    id: "KH-014",
    name: "Đỗ Thị Nga",
    category: "other",
    address: "34 Trần Hưng Đạo, TP. Huế",
    email: "dothinga@gmail.com",
    phone: "0956789013",
    gender: "female",
    note: "Chưa xác định ngành nghề cụ thể, cần tư vấn thêm.",
  },
  {
    id: "KH-015",
    name: "Vũ Anh Dũng",
    category: "real_estate",
    address: "67 Nguyễn Đình Chiểu, Quận 3, TP. Hồ Chí Minh",
    email: "vuanhdung@gmail.com",
    phone: "0967890124",
    gender: null,
    note: "",
  },
]

export const customerMockData = customerSchema.array().parse(customersData)
